export const SET_ALL_ARTICLES = "SET_ALL_ARTICLES";
export const SET_FILTERED_ARTICLES = "SET_FILTERED_ARTICLES";
export const SET_FULL_ARTICLE = "SET_FULL_ARTICLE";
export const SET_LOADING = "SET_LOADING";
export const SET_SEARCH_INPUT = "SET_SEARCH_INPUT";
export const SET_SOURCES = "SET_SOURCES";
export const SET_SELECTED_SOURCE = "SET_SELECTED_SOURCE";
